kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: st-claim-for-vuejs-frtend-app
 annotations:
   volume.beta.kubernetes.io/storage-class: "api-nfs-storage"
spec:
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 1Gi
